### PR TITLE
Replacing UnescapeDataString with UrlDecode

### PR DESCRIPTION
**Pull request by roly445**
https://blogs.msdn.microsoft.com/yangxind/2006/11/08/dont-use-net-system-uri-unescapedatastring-in-url-decoding/

### CODE REVIEW

**Comment by TrevorPilley** [comment]
Hi @roly445 can we find a way around this without having to pull in System.Web? The .NET 4.0 build of this library is client profile so it would be good to avoid that dependency. Also, can you provide a unit test for this too which would fail without this change?

**Comment by roly445** [comment]
Yes, if you do the replace before the the Uri parse then that will work.  As right now if you have the following in the request `TG9yZW0gaXBzdW0gZG9s%2Bb3Igc2l0IGF%3D` once the Uri has been escaped it equals `TG9yZW0gaXBzdW0gZG9s+b3Igc2l0IGF=` and then the next step turns the + into a space.

Would you like to make this change yourself, or would you like me to put in a new pull request?

As for making a test that would fail without this change, in your tests you have a suit for `WhenCreatedWithPlusSignsInsteadOfSpacesInTheUrl` and if you change the Uri its using to `"http://localhost/api?$filter=Name+eq+'John%2B'&$orderby=Name+asc"`  this will fail as the result is `"http://localhost/api?$filter=Name eq 'John '&$orderby=Name asc"` and not `"http://localhost/api?$filter=Name eq 'John+'&$orderby=Name asc"`.

I hope this makes sense.

**Comment by TrevorPilley** [comment]
It would be better to add an additional test rather than altering an existing one, feel free to send it as a PR with the new test and replace before decode as you suggested - if you could send a PR to both the master and odata-4 branches that would be great!

**Comment by TrevorPilley** [comment]
I had some time today so I've done a change for this - keep your eyes peeled for 3.3.6

**Comment by roly445** [comment]
That's fantastic.  My wife will be happy as I had put some time aside at the weekend for this!

**Pull request closed without merging**
